name: ssmdc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dart_pg: ^1.1.5
  mutex: ^3.0.1
  p3p:
    path: ../p3p.dart
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
